reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
  
reference_build: &reference_build
  os: linux
  env: *reference_jdk

language: minimal

os:
  - osx
  - windows
  - *reference_os

env:
  global:
    # Convenience variables for shortening commands
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    
before_install:
    - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
    - source $GRAVIS/install-jdk
    
before_cache:
  - $GRAVIS/clean-gradle-cache
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - java -version
  - sbt test

branches:
  only:
    - master
    - develop
    
notifications:
  email:
    on_success: never
    recipients:
      - federico.orazi@studio.unibo.it
      - maichol.dadi@studio.unibo.it
      - lorenzo.simoncini2@studio.unibo.it